# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 15:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perference', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(1), django.core.validators.MinLengthValidator(1)])),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(4), django.core.validators.MinLengthValidator(4)])),
                ('section', models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)])),
                ('course_id', models.CharField(max_length=8)),
                ('course_name', models.CharField(max_length=255)),
                ('instructor_name', models.CharField(max_length=255)),
                ('instructor_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(8), django.core.validators.MinLengthValidator(8)])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('quest_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('current_program', models.CharField(max_length=50)),
                ('citizenship', models.BooleanField(default=False)),
                ('student_visa', models.BooleanField(default=False)),
                ('student_visa_expiry_date', models.DateField()),
                ('enrolled', models.CharField(max_length=10)),
                ('cv', models.FileField(blank=True, upload_to='documents/')),
                ('past_position_one', models.CharField(blank=True, max_length=255)),
                ('past_position_two', models.CharField(blank=True, max_length=255)),
                ('past_position_three', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taform.Course'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taform.Student'),
        ),
    ]
