# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 02:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preference',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(10000000)]),
        ),
    ]
