# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 02:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taform', '0002_auto_20170707_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preference',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='past_position_one',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='past_position_three',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='past_position_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_visa_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
