# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 09:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taform', '0003_auto_20170707_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='course',
            name='reason',
        ),
        migrations.AddField(
            model_name='application',
            name='preference',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='application',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
